name: Link Jira issue key in PR

on: 
  pull_request:
    types: [opened]

jobs:
  jira-issue-link:
    runs-on: ubuntu-latest
    steps:
     - name: debug
       run: echo '::hello world'
       
     - name: Login
       uses: atlassian/gajira-login@master
       env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
     - name: Extract branch name
       shell: bash
       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
       id: extract_branch

     - name: Find in commit messages
       uses: atlassian/gajira-find-issue-key@master
       id: find
       with:
         from: branch
         

     - name: debug2
       run: echo "::workflow-command parameter1=${{ steps.extract_branch.outputs.branch }},${{steps.find.outputs.issue}},${{steps.outputs.issue}} ${{steps.outputs.issue}}, ${{BRANCH_NAME}}, ${{steps.find.outputs}}"

     - name: Update PR body
       uses: AsasInnab/pr-body-action@v1
       if: steps.find.outputs.issue != ''
       with:
         body: "[${{ steps.find.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.find.outputs.issue }})\n${{ github.event.pull_request.body }}"
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
